# RBAC configuration for test-runner Job
# Provides necessary permissions for the test framework to query Kubernetes services

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-runner
  namespace: default
  labels:
    app: test-runner
    component: testing

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: test-runner
  namespace: default
  labels:
    app: test-runner
    component: testing
rules:
  # Allow getting and listing services (for service discovery and health checks)
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]

  # Allow getting pods (for debugging if needed)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

  # Allow getting pod logs (for debugging if needed)
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-runner
  namespace: default
  labels:
    app: test-runner
    component: testing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test-runner
subjects:
  - kind: ServiceAccount
    name: test-runner
    namespace: default
