# Jaeger All-in-One Deployment for Test Coverage Visualization
# Provides trace collection, storage, and UI for analyzing test coverage
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: default
  labels:
    app: jaeger
    component: collector
spec:
  type: ClusterIP
  ports:
  - name: grpc-jaeger
    port: 14250
    targetPort: 14250
    protocol: TCP
  - name: http-jaeger
    port: 14268
    targetPort: 14268
    protocol: TCP
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  - name: otlp-http
    port: 4318
    targetPort: 4318
    protocol: TCP
  selector:
    app: jaeger
    component: all-in-one

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-query
  namespace: default
  labels:
    app: jaeger
    component: query
spec:
  type: ClusterIP
  ports:
  - name: query-http
    port: 16686
    targetPort: 16686
    protocol: TCP
  selector:
    app: jaeger
    component: all-in-one

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-agent
  namespace: default
  labels:
    app: jaeger
    component: agent
spec:
  type: ClusterIP
  ports:
  - name: compact
    port: 6831
    targetPort: 6831
    protocol: UDP
  - name: binary
    port: 6832
    targetPort: 6832
    protocol: UDP
  - name: http
    port: 5778
    targetPort: 5778
    protocol: TCP
  selector:
    app: jaeger
    component: all-in-one

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: default
  labels:
    app: jaeger
    component: all-in-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      component: all-in-one
  template:
    metadata:
      labels:
        app: jaeger
        component: all-in-one
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:1.52
        env:
        # Collector configuration
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
        - name: COLLECTOR_ZIPKIN_HOST_PORT
          value: ":9411"

        # Storage configuration (in-memory for testing)
        - name: SPAN_STORAGE_TYPE
          value: "memory"
        - name: MEMORY_MAX_TRACES
          value: "10000"

        # Query configuration
        - name: QUERY_BASE_PATH
          value: "/"

        # Log level
        - name: LOG_LEVEL
          value: "info"

        ports:
        # Collector ports
        - name: grpc-jaeger
          containerPort: 14250
          protocol: TCP
        - name: http-jaeger
          containerPort: 14268
          protocol: TCP
        - name: otlp-grpc
          containerPort: 4317
          protocol: TCP
        - name: otlp-http
          containerPort: 4318
          protocol: TCP

        # Agent ports
        - name: compact
          containerPort: 6831
          protocol: UDP
        - name: binary
          containerPort: 6832
          protocol: UDP
        - name: agent-http
          containerPort: 5778
          protocol: TCP

        # Query/UI port
        - name: query-http
          containerPort: 16686
          protocol: TCP

        # Admin port
        - name: admin
          containerPort: 14269
          protocol: TCP

        # Zipkin port (optional)
        - name: zipkin
          containerPort: 9411
          protocol: TCP

        resources:
          limits:
            memory: 1Gi
            cpu: 500m
          requests:
            memory: 512Mi
            cpu: 200m

        livenessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 30
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /
            port: 14269
          initialDelaySeconds: 10
          periodSeconds: 5

---
# Optional: Persistent Volume for trace storage
# Uncomment if you want to persist traces across pod restarts
#
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: jaeger-storage
#   namespace: default
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi
#
# Then add to Deployment:
# spec:
#   template:
#     spec:
#       containers:
#       - name: jaeger
#         env:
#         - name: SPAN_STORAGE_TYPE
#           value: "badger"
#         - name: BADGER_DIRECTORY_VALUE
#           value: "/badger/data"
#         - name: BADGER_DIRECTORY_KEY
#           value: "/badger/key"
#         volumeMounts:
#         - name: jaeger-storage-vol
#           mountPath: /badger
#       volumes:
#       - name: jaeger-storage-vol
#         persistentVolumeClaim:
#           claimName: jaeger-storage
